### ISSUE TITLE
Update docs configuration file to match the buildout config

### ISSUE THREAD

**Issue by huard** [bird-house/cookiecutter-birdhouse#1]

**Comment by huard** [comment]
@cehbrecht I'm a complete noob with buildout, but it seems that at the moment the sphinx config is not downloaded from birdhousebuilder.recipe.sphinx, correct? Is this something that is done for the other birds?

**Comment by cehbrecht** [comment]
@huard I have removed the sphinx recipe from the `buildout.cfg`. The recipe does not do much anymore ... it is just copying a common sphinx config file ... but each bird may have its own.
