### ISSUE TITLE
Reference cockiecutter documentation in developer guide

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#11]
## Description

Make sure people can find the cockiecutter. 
Reference it in the developer guide (wiki, birdhouse docs). 

Before we really want to advertise it we need to use it by our-self. 

## Additional Information

* https://github.com/bird-house/bird-house.github.io/wiki/Make-Your-Own-Bird
* http://birdhouse.readthedocs.io/en/latest/dev_guide.html

**Comment by huard** [comment]
Agreed. I want to create the Finch bird with it. Should I wait for you to work on the ansible deployment first?

**Comment by cehbrecht** [comment]
No, don't wait for the Ansible. Ansible deployment is also an evolving thing and needs some iterations. We can update the birds and cookiecutter later on. Basically we just need to remove the `buildout.cfg` and update the `Makefile`.

**Comment by cehbrecht** [comment]
Done.
