### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#23]
## Description

Add a `CONTRIBUTE` file to cookiecutter and template which is shown on GitHub.

Links:
* https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
* https://github.com/audreyr/cookiecutter-pypackage/blob/master/CONTRIBUTING.rst
* https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst
* https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/CONTRIBUTING.md

## Additional Information

See: https://github.com/bird-house/emu/issues/15

**Comment by cehbrecht** [comment]
I have made a start with #24. 

The shorter the text the more likely it will be read. 

We could use a common contriubution guide:
http://birdhouse.readthedocs.io/en/latest/contributing.html

... and just adding local highlights.

**Comment by huard** [comment]
Looks good.
