### ISSUE TITLE
Collect review for cookiecutter and new deployment

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#30]
## Description

Cookiecutter generates a new PyWPS service using a simplified deployment just relying on Werkzeug and Conda. A system installation can be done using Ansible. We need to see if users accept it :)

**Comment by huard** [comment]
There seems to be a way to run the playbook in a virtualenv: https://stackoverflow.com/questions/20040141/ansible-command-from-inside-virtualenv

Is this something we want to support ?

**Comment by huard** [comment]
In http://ansible-wps-playbook.readthedocs.io/en/latest/testing.html#docker
Where is the demo/ folder ?

**Comment by huard** [comment]
Otherwise the docker install works like a charm.

**Comment by cehbrecht** [comment]
@huard Thanks for review :)

I have cleaned up the docs (there is no demo) and added `become: yes` to the playbook.

The virtualenv would be an alternative to a conda env?

The idea of the Ansible playbook is to install the PyWPS app with dependencies in a Conda environment. Ansible, miniconda, nginx, supervisor, ... are installed in the system. Unlike with the buildout set-up  "sudo" privileges are required. But the birds can still be used without Ansible for demo and development with the familiar "make clean install start" step, just relying on Conda and Werkzeug.

**Comment by tomLandry** [comment]
Wow that retroaction loop is tight. Love to see that, great work both of you.

**Comment by huard** [comment]
I meant conda env, not virtualenv. Sorry. 

I also tried to make install and that still works fine. 

Got it, so really geared toward containerization. Makes sense. 

I know nothing about ansible, but is it good practice to set member:true to the whole playbook or it should split between system and user content ? Again, maybe irrelevant for docker.

**Comment by cehbrecht** [comment]
The current ansible playbook is only meant for system installation. I haven't realy perpared a new docker deployment. Since we want to have micro-services and I can (hopefully) rely on configurable existing containers for nginx and postgres I might not need Ansible for a pywps container. I could just use a jinja template and an `entrypoint.sh` script to make it configurable.

**Comment by huard** [comment]
- There is a templates/ directory that is created in the bird with cookiecutter language. Is that expected ? 
- Changing the default.cfg for the server url does not seem to affect the babybird client. If I change the url, it does not get picked up by the get_host function in cli.py.

**Comment by nilshempelmann** [comment]
- including a general link to the birdhouse Doc Top level ( https://birdhouse.readthedocs.io/en/latest/index.html )

- include a user_guide section with birdy command and python syntax

**Comment by cehbrecht** [comment]
done.
