### ISSUE TITLE
Add templates to build docker image

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#5]
## Description

Current template is missing the `Dockerfile` and `docker-compose.yml` to build and run a docker container. We could use the existing example of the Emu WPS. 

If this is *not urgent* for the new Birds "Finch" and "Kingfisher" we could wait until the Docker image creation is enhanced to meet the requirements of Docker orchestration systems. Currently we only use Docker for demo and testing.

**Comment by cehbrecht** [comment]
`Dockerfile` and `docker-compose.yml` template still have issues.
See: https://github.com/cp4cds/copernicus-wps-demo/issues/27

**Comment by cehbrecht** [comment]
Update also the "template" documentation with a docker usage example.

**Comment by cehbrecht** [comment]
See work done in finch:
https://github.com/bird-house/finch/pull/8

And also pywps demo:
https://github.com/geopython/pywps-flask/tree/master/docker

**Comment by cehbrecht** [comment]
The current docker configuration is using the Werkzeug WSGI service:
http://werkzeug.pocoo.org/docs/0.14/serving/

The Werkzeuge WSGI service is only recommended for testing and development. 

We might want to use [gunicorn](https://gunicorn.org/) in addition with Ningx and postgres. This is done with the Ansible deployment for VM/blade servers:
https://github.com/bird-house/ansible-wps-playbook

Some work on this is done in Finch WPS: bird-house/finch#8

**Comment by cehbrecht** [comment]
We might not need Nginx in the docker-compose ... Kubernetes has its own nginx/web-service. Maybe the werkzeug WSGI is sufficient for docker containers ... they are just through-away products. A shared postgres DB can be configured and added the Kubernetes set-up.

**Comment by huard** [comment]
Is this done? I see a Dockerfile in the template.

**Comment by cehbrecht** [comment]
I think we have a working version. We can improve it and open new issues.
