### ISSUE TITLE
Keep only a single "hello" process

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#53]
## Description

We currently have a few example processes in the template copied from Emu. Usually when creating a new *bird* one has to remove them manually. We could just keep a simple *hello* process to have a working example and reference in the documentation the processes of Emu. 

## Environment

* Cookiecutter version used, if any: 0.3
* Python version, if any:
* Operating System:

**Comment by huard** [comment]
+1
