### ISSUE TITLE
How to update existing birds with latest from Cookiecutter template?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#61]
## Description

We consistently improve the template while we are using the WPS birds. What could be ways to update existing birds with the improvements?

## Environment

* Cookiecutter version used, if any:
* Python version, if any:
* Operating System:

**Comment by cehbrecht** [comment]
Collecting ideas ...

It could be helpful to keep the cookiecutter settings to re-run the cookiecutter. The generated bird can be compared with the existing bird using (git) diff.

**Comment by cehbrecht** [comment]
See also for improving test-suite:
https://github.com/bird-house/bird-house.github.io/issues/28

**Comment by huard** [comment]
I was thinking more of a git command. Something like : go back to the original cookie-cutter commit, create the new version then apply all the other changes.

**Comment by huard** [comment]
I think that the procedure would then look like this:

```
git co -b orig_cookiecutter_update <SHA of the first commit>
git clean -fxd
# Run cookie-cutter with extra context arguments reflecting how it was called the first time.
git add * 
git add */.*
git ci -m 'update cookiecutter template'
git co -b cookiecutter_update master
git merge orig_cookiecutter_update
```

@cehbrecht One issue is that the date is going to be updated, because the jinja template uses the current date. This will screw the CHANGES.rst file 
```
-0.1.0 (2018-04-16)
+0.1.0 (2020-01-10)
```
Cookiecutter should probably then take the date as an argument, so we can pass the original date of creation.

**Comment by cehbrecht** [comment]
We could tune the template more to avoid potential conflicts when updating with the script in PR #79.
