### ISSUE TITLE
Improve Makefile and maintenance across Birds

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/cookiecutter-birdhouse#7]
## Description

Currently all Birds have a common `Makefile` which is pulled from https://github.com/bird-house/birdhousebuilder.bootstrap using `make selfupdate` command.

* have a look at cookiecutter `Makefile` examples to enhance the current template.
* can we improve the update mechanism of common `Makefile`.

**Comment by cehbrecht** [comment]
Python [Paver](https://pypi.org/project/Paver/) might be a valuable replacement for Makefile. At least it would simplify the bootstrap ... don't need to install Makefile in the system.

**Comment by cehbrecht** [comment]
Alternative to Paver could be [Invoke](http://www.pyinvoke.org/index.html)

**Comment by huard** [comment]
The current Makefile in cookiecutter has no `stop` and `status` commands.

**Comment by cehbrecht** [comment]
Makefile `stop` and `status` targets are related to:
https://github.com/bird-house/emu/issues/35

**Comment by cehbrecht** [comment]
`stop` and `status` targets added in PR #34.

**Comment by cehbrecht** [comment]
See issue #61.

**Comment by cehbrecht** [comment]
close it as duplicate of #61.
