### ISSUE TITLE
doc links not working on github's view of readme 

### ISSUE THREAD

**Issue by fmigneault** [bird-house/cookiecutter-birdhouse#77]
All links such as ``` `file:`Dockerfile` ``` are not working when clicking on them from github's ui view in the README.
This can be fixed by replacing them with references in the .rst (resolves on github side) and providing the root path of the repo to the `conf.py` to preserve resolution during building docs on readthedocs and in shell.
You can check  https://github.com/ouranosinc/magpie 's `README.rst` and `docs/conf.py` files for a working setup with above description.

**Comment by Zeitsperre** [comment]
This has been rendered obsolete by modern changes to the template.
